stages:
  load_data: 
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - "original dataset/Microsoft_Stock.csv"
    outs:
    - data/raw/Microsoft_Stock.csv

