base:
  project: 'Microsoft Stock Time Series'
  random_state: 42
  target_col: Volume

data_source:
  s3_source: 'original dataset/Microsoft_Stock.csv'

load_data:
  raw_dataset_csv: data/raw/Microsoft_Stock.csv

split_data:
  train_path: data/processed/train_Microsoft_Stock.csv
  test_path: data/processed/test_Microsoft_Stock.csv
  test_size: 0.8

estimators:
  model:
    epoch: 50
    learning_rate = 0.01

model_dir: saved_model/model.pth